#!/bin/sh
flake8 --max-line-length 88 --extend-ignore E203 --extend-exclude build/ --show-source --statistics setup.py term_img/ tests/
echo
black --check --diff --color setup.py term_img/ tests/
echo
pytest -v "--ignore-glob=*url*" tests/
